name: CI Initialise

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
      - name: Print CI Initialising Message
        run: echo "CI step initialising"